version: "3"

services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - db-data:${DB_DATA_PATH}
    networks:
      - project
    ports:
      - ${DB_OUT_PORT}:${DB_INTER_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: ${DB_DATA_PATH}

  backend:
    build: ./dockerfiles/general
    volumes:
      - ../backend:/opt/app
    networks:
      - project
    ports:
      - 5021:3000
    depends_on:
      - db
    working_dir: /opt/app
    command: npm run start:dev
    env_file:
      - ./.env

  frontend:
    build: ./dockerfiles/general
    volumes:
      - ../frontend:/opt/app
    networks:
      - project
    env_file:
      - ./.env

volumes:
  db-data:

networks:
  project:
    driver: bridge
  nginx:
    external:
      name: nginx
