version: "3"

services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - ../db:/var/lib/postgresql/data
    networks:
      - project
    ports:
      - 3021:5432
    env_file: ./env/common.env

  frontend:
    build: ./dockerfiles/general
    volumes:
      - ../frontend:/opt/app
    networks:
      - project
    env_file:
      - ./env/common.env
      - ./env/frontend.env

networks:
  project:
    driver: bridge
  nginx:
    external:
      name: nginx
